<?php

return [
    'default_resource' => 'products',

    'per_page_options' => [10, 25, 50, 100],

    'resources' => [
        'products' => [
            'label' => 'Sản phẩm',
            'description' => 'IMEI, thông tin kho, bảo hành và QR.',
            'icon' => 'SP',
            'table' => 'products',
            'primary_key' => 'id',
            'default_sort' => ['id', 'desc'],
            'searchable' => ['product_code', 'name', 'imei', 'warranty_status'],
            'columns' => [
                ['key' => 'id', 'label' => 'ID', 'type' => 'number'],
                ['key' => 'product_code', 'label' => 'Mã hàng', 'type' => 'text'],
                ['key' => 'name', 'label' => 'Tên hàng', 'type' => 'text'],
                ['key' => 'imei', 'label' => 'IMEI', 'type' => 'mono'],
                ['key' => 'warehouse_date', 'label' => 'Ngày nhập', 'type' => 'date'],
                ['key' => 'warranty_months', 'label' => 'Thời hạn', 'type' => 'months', 'list' => false],
                ['key' => 'warranty_expires_at', 'label' => 'Ngày hết hạn', 'type' => 'date'],
                ['key' => 'warranty_status', 'label' => 'Trạng thái', 'type' => 'warranty_status'],
                ['key' => 'internal_note', 'label' => 'Ghi chú nội bộ', 'type' => 'long_text', 'list' => false],
                ['key' => 'qr_token', 'label' => 'QR token', 'type' => 'masked_token', 'list' => false, 'sensitive' => true],
                ['key' => 'created_by', 'label' => 'Người tạo (ID)', 'type' => 'number', 'list' => false],
                ['key' => 'updated_by', 'label' => 'Người cập nhật (ID)', 'type' => 'number', 'list' => false],
                ['key' => 'created_at', 'label' => 'Ngày tạo', 'type' => 'datetime', 'list' => false],
                ['key' => 'updated_at', 'label' => 'Ngày cập nhật', 'type' => 'datetime', 'list' => false],
                ['key' => 'deleted_at', 'label' => 'Ngày xóa mềm', 'type' => 'datetime'],
            ],
        ],

        'users' => [
            'label' => 'Người dùng',
            'description' => 'Tài khoản nội bộ và trạng thái truy cập.',
            'icon' => 'ND',
            'table' => 'users',
            'primary_key' => 'id',
            'default_sort' => ['id', 'desc'],
            'searchable' => ['name', 'email'],
            'columns' => [
                ['key' => 'id', 'label' => 'ID', 'type' => 'number'],
                ['key' => 'name', 'label' => 'Họ tên', 'type' => 'text'],
                ['key' => 'email', 'label' => 'Email', 'type' => 'text'],
                ['key' => 'email_verified_at', 'label' => 'Xác minh email', 'type' => 'datetime', 'list' => false],
                ['key' => 'is_active', 'label' => 'Hoạt động', 'type' => 'boolean'],
                ['key' => 'created_at', 'label' => 'Ngày tạo', 'type' => 'datetime'],
                ['key' => 'updated_at', 'label' => 'Ngày cập nhật', 'type' => 'datetime', 'list' => false],
            ],
        ],

        'import_batches' => [
            'label' => 'Lịch sử import',
            'description' => 'Kết quả các lần nhập dữ liệu Excel và CSV.',
            'icon' => 'IM',
            'table' => 'import_batches',
            'primary_key' => 'id',
            'default_sort' => ['id', 'desc'],
            'searchable' => ['original_filename'],
            'columns' => [
                ['key' => 'id', 'label' => 'ID', 'type' => 'number'],
                ['key' => 'user_id', 'label' => 'Người thực hiện (ID)', 'type' => 'number'],
                ['key' => 'original_filename', 'label' => 'Tên file', 'type' => 'text'],
                ['key' => 'total_rows', 'label' => 'Tổng dòng', 'type' => 'number'],
                ['key' => 'success_rows', 'label' => 'Thành công', 'type' => 'number'],
                ['key' => 'failed_rows', 'label' => 'Lỗi', 'type' => 'number'],
                ['key' => 'errors', 'label' => 'Chi tiết lỗi', 'type' => 'json_count', 'list' => false, 'sensitive' => true],
                ['key' => 'completed_at', 'label' => 'Hoàn tất', 'type' => 'datetime'],
                ['key' => 'created_at', 'label' => 'Ngày tạo', 'type' => 'datetime', 'list' => false],
                ['key' => 'updated_at', 'label' => 'Ngày cập nhật', 'type' => 'datetime', 'list' => false],
            ],
        ],

        'roles' => [
            'label' => 'Vai trò',
            'description' => 'Các vai trò phân quyền trong hệ thống.',
            'icon' => 'VT',
            'table' => 'roles',
            'primary_key' => 'id',
            'default_sort' => ['id', 'asc'],
            'searchable' => ['name', 'guard_name'],
            'columns' => [
                ['key' => 'id', 'label' => 'ID', 'type' => 'number'],
                ['key' => 'name', 'label' => 'Tên vai trò', 'type' => 'text'],
                ['key' => 'guard_name', 'label' => 'Guard', 'type' => 'text'],
                ['key' => 'created_at', 'label' => 'Ngày tạo', 'type' => 'datetime'],
                ['key' => 'updated_at', 'label' => 'Ngày cập nhật', 'type' => 'datetime', 'list' => false],
            ],
        ],

        'permissions' => [
            'label' => 'Quyền hạn',
            'description' => 'Danh sách quyền được cấp cho các vai trò.',
            'icon' => 'QH',
            'table' => 'permissions',
            'primary_key' => 'id',
            'default_sort' => ['id', 'asc'],
            'searchable' => ['name', 'guard_name'],
            'columns' => [
                ['key' => 'id', 'label' => 'ID', 'type' => 'number'],
                ['key' => 'name', 'label' => 'Tên quyền', 'type' => 'text'],
                ['key' => 'guard_name', 'label' => 'Guard', 'type' => 'text'],
                ['key' => 'created_at', 'label' => 'Ngày tạo', 'type' => 'datetime'],
                ['key' => 'updated_at', 'label' => 'Ngày cập nhật', 'type' => 'datetime', 'list' => false],
            ],
        ],
    ],
];
